---
name: Tests for pueblo.ngr

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/ngr.yml'
    - 'pueblo/ngr/**'
    - 'tests/ngr/**'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/ngr.yml'
    - 'pueblo/ngr/**'
    - 'tests/ngr/**'

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.12"]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    # Needed for `pueblo.ngr`.
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26.1'
        elixir-version: '1.15'
    - name: Set up Elixir/Mix dependency cache
      uses: actions/cache@v3
      id: elixir-mix-cache
      with:
        path: tests/ngr/elixir/deps
        key: ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-mix-${{ hashFiles('tests/ngr/elixir/mix.lock') }}

    # Needed for `pueblo.ngr`.
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    # Needed for `pueblo.ngr`.
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true

    - name: Set up project
      run: |

        # `setuptools 0.64.0` adds support for editable install hooks (PEP 660).
        # https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6400
        pip install --upgrade 'setuptools>=64'

        # Install package in editable mode.
        pip install --use-pep517 --prefer-binary --editable='.[cli,develop,test]'

    - name: Run linter and software tests
      run: |
        pytest -m ngr

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: ngr
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
