---
name: Tests for pueblo.ngr

on:
  pull_request:
    paths:
    - '.github/workflows/ngr.yml'
    - 'pueblo/ngr/**'
    - 'tests/ngr/**'
    - 'pyproject.toml'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/ngr.yml'
    - 'pueblo/ngr/**'
    - 'tests/ngr/**'
    - 'pyproject.toml'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.8"
          - "3.14"
          - "3.14t"

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        activate-environment: 'true'
        cache-suffix: ${{ matrix.python-version }}
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    # Needed for `pueblo.ngr`.
    - name: Install Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26.1'
        elixir-version: '1.15'
    - name: Install Elixir/Mix dependency cache
      uses: actions/cache@v5
      id: elixir-mix-cache
      with:
        path: tests/ngr/elixir/deps
        key: ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-mix-${{ hashFiles('tests/ngr/elixir/mix.lock') }}

    # Needed for `pueblo.ngr`.
    - name: Install Java
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"

    # Needed for `pueblo.ngr`.
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "4.0.3"
        bundler-cache: true

    - name: Install project
      run: |
        uv pip install --upgrade --editable='.[cli,develop,test]'

    - name: Run linter and software tests
      run: |
        pytest -m ngr

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
