---
name: Tests for pueblo.sfa

on:
  pull_request:
  push:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  sfa-minimal:
    name: SFA minimal on Python ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.8"
          - "3.14"
          - "3.14t"

    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        activate-environment: 'true'
        cache-suffix: ${{ matrix.python-version }}
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install project
      run: |
        uv pip install --upgrade --editable='.[develop,test]'

    - name: Run linter and software tests
      run: |
        pytest -m sfa

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true

  sfa-full:
    name: SFA full on Python ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.8"
          - "3.14"
          - "3.14t"

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        activate-environment: 'true'
        cache-suffix: ${{ matrix.python-version }}
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install project
      run: |
        uv pip install --upgrade --editable='.[develop,test,sfa-full]'

    - name: Run linter and software tests
      run: |
        pytest -m sfa

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
